FROM node:18-alpine AS development
ENV NODE_ENV development

WORKDIR /app

# Cache and Install dependencies
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

# Start the app
CMD [ "npm", "run", "dev" ]