services: # los servicios son los contenedores que se ejecutan
  # servicio para la API de node
  api:
    build: # Define cómo construir la imagen Docker
      context: . # Directorio donde Docker buscará los archivos para construir la imagen
      dockerfile: Dockerfile # Le dice a Docker que use el Dockerfile en el directorio actual para construir la imagen
    container_name: api
    ports:
      - "5001:5000"
    env_file:
      - .env # Carga las variables de entorno desde el archivo .env
    volumes: # Mapea los directorios locales con los directorios dentro del contenedor
      - .:/app  # Mapea todo el directorio actual, así podrá obtener el package.json para ejecutar el script "start"
    depends_on:
      - mongo # Asegura que MongoDB se inicie antes de la API
  

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db # Volumen para persistir los datos de MongoDB
    ports:
      - "27017:27017"

volumes:
  mongo-data: {}